# Generated by Django 5.0.7 on 2024-08-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_delete_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
